GET http://localhost:8080/

###

POST http://localhost:8080/echo
Content-Type: application/json

{
    "name": "Sri Ganesh Thota",
    "email": "sriganeshthota12345@gmail.com",
    "password": "password"
}

###

GET http://localhost:8080/hey/Sri%20Ganesh%20Thota

###

GET http://localhost:8080/users/

###

GET http://localhost:8080/users/1

###

POST http://localhost:8080/users/
Content-Type: application/json

{
    "name": "Sri Ganesh Thota"
}

###

PUT http://localhost:8080/users/2
Content-Type: application/json

{
    "name": "Thota Sri Ganesh"
}

###

DELETE http://localhost:8080/users/2

###